version: "3.8"

services:
  sdf-2d-demo:
    init: true
    image: schmelczera/sdf-2d-demo
    networks:
      - network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 16M
        reservations:
          cpus: "0.1"
          memory: 16M
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      restart_policy:
        condition: on-failure
        window: 30s

networks:
  network:
    driver: overlay
